lib/xdrgen/generators/java/XdrDataInputStream.erb
lib/xdrgen/generators/java/XdrDataOutputStream.erb

`pad` methods in both `XdrDataInputStream` and `XdrDataOutputStream` were wrong. For `mCount` equal 4 they should pad/skip 0 bytes but were padding/skipping 4.

Fix padding in Java

---

lib/xdrgen/generators/java.rb

My 1yo commit I forgot to merge. It fixes `decode` method in Java (`discriminant` value was not read). I used this to generate Java classes when XDR changed last year so they are OK.
Example, `Memo` class diff:
```diff
diff --git a/src/main/java/org/stellar/sdk/xdr/Memo.java b/src/main/java/org/stellar/sdk/xdr/Memo.java
index e04bf25..d66c5d2 100644
--- a/src/main/java/org/stellar/sdk/xdr/Memo.java
+++ b/src/main/java/org/stellar/sdk/xdr/Memo.java
@@ -80,8 +80,10 @@ public static void encode(XdrDataOutputStream stream, Memo encodedMemo) throws I
}
}
public static Memo decode(XdrDataInputStream stream) throws IOException {
-    Memo decodedMemo = new Memo();
-    switch (decodedMemo.getDiscriminant()) {
+  Memo decodedMemo = new Memo();
+  MemoType discriminant = MemoType.decode(stream);
+ …
```

Fix decode in render_union in java

---

lib/xdrgen/generators/java/XdrDataInputStream.erb
lib/xdrgen/generators/java/XdrDataOutputStream.erb

This commit contains several bugfixes and improvements:
- `XdrDataOutputStream` class is now padding opaque data.
- `XdrDataInputStream` class is now throwing an IOException when padding
bytes are not zeros.
- Made methods that shouldn't be used outside of `XdrDataOutputStream`
and `XdrDataInputStream` classes private.
- Removed unused imports and variables.

Fix XDR Data Stream in Java

---

lib/xdrgen/generators/java/XdrDataInputStream.erb

`XdrInputStream.pad()` method was calling internal `InputStream` `read()`
method without updating the internal `mCount` counter. This was fixed by
using `XdrInputStream.read()` wrapper that handles counter updates.
CC: https://github.com/stellar/java-stellar-sdk/issues/48

Fix pad() method in XdrInputStream

---

lib/xdrgen/generators/go.rb

Adds `MarshalBinary` and `UnmarshalBinary` for each rendered definition, implementing the binary interfaces from [the standard encoding package](https://golang.org/pkg/encoding/).

Implement standard binary interfaces in Go output

---

lib/xdrgen/ast/definitions/union.rb
lib/xdrgen/generators/go.rb
lib/xdrgen/generators/java.rb
lib/xdrgen/generators/javascript.rb

`Union.resolved_case` doesn't support unions with standard type discriminant and constant (`const`) values, ex:
```xdr
enum StellarValueType
{
STELLAR_VALUE_BASIC = 0,
STELLAR_VALUE_SIGNED = 1
};
union switch (int v)
{
case STELLAR_VALUE_BASIC:
void;
...
```
To fix this, we are searching for identifier in namespace's enum constants if discriminant type has not been found.
EDIT, realized that it probably doesn't work for JS and Java too:

Support for standard type union discriminant with constant value

---

.gitignore
lib/xdrgen/generators/java.rb
lib/xdrgen/generators/java/XdrElement.erb

Add a common parent XdrElement interface.
Currently has a single convenience method so you can call encode directly on any XDR element without having to call the static method on the right class.
The main use for this is being able to reflect on classes and doing e.g. some kotlin extension functions.
Currently the java code does not compile because of #36 but this issue also occurs on master. My ruby is a bit rusty so would appreciate some help with that issue.

Java parent interface for xdr

---

lib/xdrgen/generators/java.rb
lib/xdrgen/generators/java/XdrDataInputStream.erb
lib/xdrgen/generators/java/XdrDataOutputStream.erb
lib/xdrgen/generators/java/XdrString.erb

According to https://github.com/stellar/go/issues/2022 XDR strings are equivalent to XDR opaque fields. The Java XDR code generator represents XDR strings as Java Strings. This representation is incorrect because an XDR string has no restrictions on the byte format. It is possible for an XDR string to contain invalid ASCII or invalid unicode bytes. The safest representation of an XDR string is a byte array.

Represent XDR strings as bytes

---

lib/xdrgen/generators/elixir.rb
lib/xdrgen/generators/javascript.rb

While generating protocol 14 XDRs,  I noticed a weird output for CAP33 related enums and ops.
The following:
```
beginSponsoringFutureReserf: 16,
endSponsoringFutureReserf: 17,
```
Should have been 
```
beginSponsoringFutureReserves: 16,
endSponsoringFutureReserves: 17,
```
After investigating, I found a bug in this library, which was comparing the pluralized version of the name with the original, the problem is that it didn't keep into account the letter casing - leading to incorrect results in scenarios like this one
```
"BEGIN_SPONSORING_FUTURE_RESERVEs" == "BEGIN_SPONSORING_FUTURE_RESERVES"
```
This PR fixes this issue, making both values down case.

Downcase value when comparing if the source is plural or singular.

---

lib/xdrgen/grammar/union.treetop
spec/fixtures/parser/union.x

Fixes #50.
Otherwise generate is failing for cases like this: https://github.com/stellar/stellar-core/blob/master/src/xdr/Stellar-transaction.x#L703-L704
```
union PathPaymentStrictReceiveResult switch (
PathPaymentStrictReceiveResultCode code)
{
case PATH_PAYMENT_STRICT_RECEIVE_SUCCESS:
struct
{
ClaimOfferAtom offers<>;
SimplePaymentResult last;
} success;
case PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER:
Asset noIssuer; // the asset that caused the error
default:
void;
};
```

Fix grammar to support multiline union header

---

lib/xdrgen/generators/java.rb

This change adds Builder static inner classes to unions and structs. e.g.
```
public static final class Builder {
private AssetType discriminant;
private AssetAlphaNum4 alphaNum4;
private AssetAlphaNum12 alphaNum12;
public Builder discriminant(AssetType discriminant) {
this.discriminant = discriminant;
return this;
}
public Builder alphaNum4(AssetAlphaNum4 alphaNum4) {
this.alphaNum4 = alphaNum4;
return this;
}
public Builder alphaNum12(AssetAlphaNum12 alphaNum12) {
this.alphaNum12 = alphaNum12;
return this;
}
public Asset build() {
Asset val = new Asset();
val.setDiscriminant(discriminant);
val.setAlphaNum4(alphaNum4);
val.setAlphaNum12(alphaNum12);
return val;
}
}
```
This pattern allows for fluent object construction in Java.

Add Builders to unions and structs

---

lib/xdrgen/generators/java.rb

This allows for convenient constructions of typedefs, e.g.
Instead of
```
Uint64 u = new Uint64();
u.setUint64(100L);
```
this
```
Uint64 u = new Uint64(100L);
```

Add constructors for typedefs in Java

---

lib/xdrgen/generators/elixir.rb
lib/xdrgen/generators/javascript.rb
lib/xdrgen/version.rb

While generating protocol 18 XDRs, I noticed a weird output for CAP-38 related attributes:
* `asseta` should have been `assetA`
* `maxAmounta` should have been `maxAmountA`
* `minAmounta` should have been `minAmountA`
I found a (likely) bug in the `pluralize` method where words ending with `ta` (or `tA`) where considered the plural form and `"AssetA".pluralize` results in `"Asseta"`.
To prevent that issue I'm now applying pluralization to the camel case version of the name, so `"ASSET_A".pluralize` results in `"ASSET_AS"`, preventing that error.

[v0.1.1] Fix pluralization for strings ending with "tA"

---

lib/xdrgen/generators/go.rb

Skip the Go generation of the binary interface on optional types.
xdrgen generates invalid Go code when the input XDR definitions contain an optional typedef in the form:
```
typedef UnderlyingType* NamedType
```
The problem with this for the Go generator is that it results in the following Go type definition:
```go
type NamedType *UnderlyingType
```
That type definition is valid, although uncommon in Go applications, because types that name a pointer type are not allowed to have methods.
Xdrgen defines the `MarshalBinary` and `UnmarshalBinary` functions for every type is generates, and so those generated functions cause the output of xdrgen to have a compile error.
It would be great to solve this problem properly, but it is complex because we need to implement the pointer type as a …

Skip Go generated binary interface on optional typedefs

---

lib/xdrgen/generators/go.rb

Change how the generated Go code marshals objects to binary to move logic from runtime to compile time. Specifically:
- Add an `EncodeTo` function to all types that takes an `xdr.Encoder` and uses the encoder to encode itself.
- Have the `EncodeTo` functions call the appropriate lower level encode function for their type, such as `EncodeUint`, instead of `Encode` that will use reflection to figure out the type.
- Have the `EncodeTo` functions of complex types (structs, unions) call the `EncodeTo` function of each of their fields.
For any types not generated, such as `time.Time`, encoding falls back to the current reflection based approach.
This change affects marshaling/encoding only, and not unmarshaling/decoding. 
For an example of how this changes generated Go code, see …

Improve the performance of Go generated marshaling/encoding code

---

lib/xdrgen/generators/go.rb

This PR switches the  `EncodeTo()` implementation for fixed opaque types (Go arrays) to a pointer received.
Otherwise (if called by value), Go will make a heap allocation for every by-value call since the copy required by the call tends to escape the stack due to the large array sizes.
This finally reduces marhsalling allocations to a bare minimum and speeds up marshaling between 20 and 40%.
Using the benchmarks from stellar/go:
Before:
```
goos: darwin
goarch: amd64
pkg: github.com/stellar/go/benchmarks
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkXDRMarshalWithReflection
BenchmarkXDRMarshalWithReflection-8                   	   95192	     13507 ns/op	    5128 B/op	     156 allocs/op
BenchmarkXDRMarshal
BenchmarkXDRMarshal-8                                 	 1081450 …
```

Ensure fixed-opaque types (arrays) implement EncodeTo() by pointer

---

lib/xdrgen/generators/go.rb

Enum econding:
* Check that enum values are legal before encoding them
* Use `e` as the receiver name of `EncodeTo` (it was using `s`) which is inconsistent with the rest of the code.
Union encoding:
* Error when a supplied discriminant doesn't match a branch ( #70 )
* When an enum is used as a discrimimnant, check that they are legal before encoding
* Use `u` as the receiver name of `EncodeTo` (it was using `s`) which is inconsistent with the rest of the code.
Layout improvements:
* Factor invocations and error checking. This makes the code more compact and removes error [S1021](https://staticcheck.io/docs/checks#S1021 from the generated code:
```diff
-       err = s.SeqNum.EncodeTo(e)
-       if err != nil {
+       if err = s.SeqNum.EncodeTo(e); err != nil {
return err
}
```
* Fix …

Add multiple EncodeTo improvements

---

lib/xdrgen/generators/go.rb

This is the decoding counterpart of https://github.com/stellar/xdrgen/pull/65
There is a dramatic performance improvement: ~13x speedup and and ~11x  allocation reduction.
Check https://github.com/stellar/go/pull/4064 for details on the speedup and the generated code.
TODO:

Generate `DecodeFrom()` methods for Golang

---

lib/xdrgen/generators/go.rb

Decoder is `d`, not `e`. Probably copy/paste error from the Encoder func.

Fix typo in go generation

---

lib/xdrgen/generators/go.rb

As per https://github.com/stellar/go/pull/4366, simplifies usage from go.

Add lint:file-ignore comments to go generator frontmatter

---

lib/xdrgen/output.rb

Expand source paths into absolute paths before finding their relative source path.
Source paths may be absolute or relative, and before we find their relative path we need to have their absolute path. This code that assumes the paths were always absolute.

Fix relative source paths

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add to the Rust generated code `Deref<Target=Vec<_>>` implementations for `VecM` and all types that are typedefs to `VecM`.
`Vec` in the stdlib has `[T]` as its Deref which is convenient, and `VecM` could do the same also for convenience. It derefs to `Vec<T>` since `[T]` comes automatically since they're automatically chained.

Rust: Add Deref<Target=Vec<_>> impls for VecMs

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/test.x/MyXDR.rs

Change Deref for VecM typedefs to be VecM instead of Vec.
I just added the Derefs, but I made the Deref target Vec for typedefs that wrap VecM. The internal type is VecM and so Deref should target that, and due to automatic chaining with Deref we'll get Vec anyway.

Change Deref for VecM typedefs

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Remove unnecessary fns on VecM that are already provided via the Deref impl to Vec.
Since the Deref impl to Vec provides the fns there is no need to reimplement them in VecM.

Remove unnecessary fns on VecM

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/test.x/MyXDR.rs

Add VecM fns and Derefs to typedefs of opaques and strings.
The code was intended to add these fns and Derefs to opaques and strings, but I had the type comparison using the wrong operatore `==` instead of `===` and in reverse, so the condition didn't match.

Fix VecM fns and Deref for opaques and strings

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add VecM<>str conversions to the Rust generated code.
VecM's are used for XDR strings.

Rust: Add VecM<>str conversions

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Clean up the String<>VecM conversions so that there are owned and non-owned conversions, and owned conversions do not allocate.
The existing conversions took owned values and then allocated unnecessarily.

Rust: Make String<>VecM conversions from borrows/owned

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add to/from xdr bytes to the Rust xdr types.
The xdr types provide convenience functions for serialization to and from base64 strings, and general readers/writers, but not byte slices/vecs. It would be convenient if it did so.

Rust: Add to/from xdr bytes

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Make to_vec not consume the vec and create a new vec. Add to_string to do same as vec but for a string.
to_ functions should not consume an owned type unless they are Copy. The to_string function is helpful because we use VecM's for strings, and it is not always convenient to try_into a string.

Rust: Fix to_vec and add to_string

---

lib/xdrgen/generators/go.rb
lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
lib/xdrgen/output.rb
spec/output/generator_spec_go/block_comments.x/MyXDR_generated.go
spec/output/generator_spec_go/const.x/MyXDR_generated.go
spec/output/generator_spec_go/enum.x/MyXDR_generated.go
spec/output/generator_spec_go/nesting.x/MyXDR_generated.go
spec/output/generator_spec_go/optional.x/MyXDR_generated.go
spec/output/generator_spec_go/struct.x/MyXDR_generated.go
spec/output/generator_spec_go/test.x/MyXDR_generated.go
spec/output/generator_spec_go/union.x/MyXDR_generated.go
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add input file SHA256 hash consts to Go/Rust generated code, injecting the following into the Stellar rs-stellar-xdr lib:
```rust
/// `XDR_FILES_SHA256` is a list of pairs of source files and their SHA256 hashes.
pub const XDR_FILES_SHA256: [(&str, &str); 6] = [
(
"xdr/curr/Stellar-SCP.x",
"8f32b04d008f8bc33b8843d075e69837231a673691ee41d8b821ca229a6e802a",
),
(
"xdr/curr/Stellar-ledger-entries.x",
"3aa135c309c2d67883f165961739b4940c90df59240d8aeef55deced8d7708b5",
),
(
"xdr/curr/Stellar-ledger.x",
"ef746ead6bb8ef9541599796804d672f2994e2599a6dc595ece099e166b49f10",
),
(
"xdr/curr/Stellar-overlay.x",
"8ecbc36d2a43103499a6416572c7cd7b4fd7638d1a2af515b81b463ce6909c51",
),
(
"xdr/curr/Stellar-transaction.x",
"45fdeb428e68d6b07e3e3157b6404567e0efb712c9d4c90a61a1035854c32b90",
),
( …
```

Add input file SHA256 hash consts to Go/Rust generated code

---

README.md

Add Rust to README.
Rust is supported, but it isn't included in the README.

Rust: Add to README

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Rename `IO` error to `Io`.
Adhere to Rust naming conventions and so that IDEs don't display the error enum value as a constant.

Rust: fix naming of IO error

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add a read_xdr_iter to all ReadXdr impls that returns an iterator for reading a stream of values from a Read impl.
In a couple places we need to read a stream of XDR values which is pretty inconvenient to impl in practice. Wrapping it into an iterator should make it much simpler.
This highlights a problem with existing read_xdr impls that they use read_exact which unfortunately obscures partial fill EOFs which could be a security concern in our uses. A TODO has been added to address this later.

Rust: add read_xdr_iter

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Remove unnecessary allow of arms matching the same result.
They are not required on these functions as it would never make sense for the enum values to map to the same values.

Rust: remove unnecessary lint ignore

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Implement the `Default` trait on `VecM` and other var array types.
`VecM` doesn't make it easy to create an empty copy of itself, and using Default is the most reasonable way of providing that functionality.

Rust: Impl Default on VecM

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

In the Rust generator make the `name` and `discriminant` fns on enums and unions `const` and add `trait`s that group these fns. Also changed the `&str` return values so that they have a `'static` lifetime.
The fns can be const fns which increases the places we can use them, and their str values are easier to use if they have a static lifetime. @graydon asked for traits so it is easier to write code across all enum / union types.
Close #108 #107 #106 
Now that we're adding traits to the generated code it is becoming more interesting to have a use case where these traits could be usable across multiple sets of generated code which would mean moving out some of the code in `types.rs` into its own crate and repo. We may like to do this down the track.

Rust: Make name, discriminant const and trait fns

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add additional conversion fns for array types to the Rust generated code.
To make it simpler to convert from slices to fixed length XDR arrays.

Rust: Add additional conversion fns for array types

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/test.x/MyXDR.rs

Add as_slice to fixed length arrays.
Convenience and consistency with other types.

Rust: Add as_slice to fixed length arrays

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Allow Rust enum variants generated for unions to have large discrepencies in size.
In some cases it may be beneficial to box the large variants, but it is difficult to distinguish them in xdrgen so we'd probably need labeling via comments in the XDR if we wanted to selectively box enum variants. We could also just box all variants, but that reduces ergonomics and isn't necessarily better. The only case we have where this is required, that is part of CAP-56's new TransactionMetaV3, isn't a problem since the largest variant will be the most common variant.
Close #115

Rust: allow large enum variants

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Initial implementation of #112.
Deserialization of `Box` and `VecM` is not implemented yet without `alloc`. Should be fixed as part of https://github.com/stellar/rs-stellar-xdr/issues/47.

Rust: Add serde json support

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add base64 feature to the Rust generated code that wraps functionality dependent on the base64 dependency.
To silo all dependency functionality behind optional dependencies.

Rust: add base64 feature

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add PartialEq implementation for the Error type that is part of the generated Rust code.
It is extremely inconvenient for testing failure cases if the Error type is not comparable.
To some degree adding a PartialEq implementation is controversial because the embedded IO error cannot be compared. The implementation compares the kind because it seems like the best broad way to compare an IO error if we can't compare it more absolutely and completely. The main use case for comparing these errors is to facilitate better testing of failure cases. So this is a trade off of a perfect comparison implementation over a useful one.

Rust: add PartialEq impl for Error

---

.github/workflows/ruby.yml

Make the complete job fail for cancelled builds, by having it run only if all the prior jobs succeed.
The complete job checks if any of the jobs failed, but they might have been cancelled rather than failed. This causes the complete job to succeed when a needed job was cancelled. You can see how this build played out where a cancelled job resulted in a merged PR: stellar/rs-stellar-xdr#130.

Fix complete ci job

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/Cargo.toml
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Sketch of code to generate https://github.com/stellar/rs-stellar-xdr/pull/132 -- support [Arbitrary](https://crates.io/crates/arbitrary) on all XDR types in Rust. Arbitrary is the standard interface to fuzzers and at least one property-testing library [arbtest](https://crates.io/crates/arbtest)

Rust: Support Arbitrary on all generated types

---

.github/workflows/ruby.yml

Change ci complete job to always run and explicitly check the results of the depended jobs.
In #126 I changed the way the complete job worked to catch cancelled jobs, but apparently I made the situation worse and caused failing jobs to be ignored, because the complete job was being skipped and skipped jobs are interpreted as success by GitHub's required checks.

Fix ci complete job (again)

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add VecM::into_opton, and related fns.
So that converting from single max-length VecM's to Option's is convenient.
Convenience function for work I'm currently doing for https://github.com/stellar/rs-soroban-sdk/issues/118.

Add VecM::into_opton, and related fns

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add VecM::to_string_lossy to Rust generated code.
To use in situations where it is okay if the strings are lossy converted and if there are non-utf8 characters we don't really care about handling them.
Close https://github.com/stellar/xdrgen/issues/131

Add VecM::to_string_lossy to Rust generated code

---

lib/xdrgen/generators/go.rb
spec/output/generator_spec_go/block_comments.x/MyXDR_generated.go
spec/output/generator_spec_go/const.x/MyXDR_generated.go
spec/output/generator_spec_go/enum.x/MyXDR_generated.go
spec/output/generator_spec_go/nesting.x/MyXDR_generated.go
spec/output/generator_spec_go/optional.x/MyXDR_generated.go
spec/output/generator_spec_go/struct.x/MyXDR_generated.go
spec/output/generator_spec_go/test.x/MyXDR_generated.go
spec/output/generator_spec_go/union.x/MyXDR_generated.go

1. Fix the generation of file hashes
2. Make sure we only generate EncodeTo by pointer for fixed opaque types or fixed opaque synonyms

Go: Misc code generation fixes

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Generate in the Rust output an enum that contains all the types being generated.
So that tools can decode all types from user input.
Close #114

Rust: Generate an enum containing all types

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Make value -> Any available in non-std builds.
It's unnecessary to have scoped it to std builds.

Rust: Make value -> Any available in non-std builds

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Add read xdr to end fns to the generated Rust code, and use them for base64 decoding.
A lot of the time when reading from a stream into a value we want to read the entire stream into that one value, and for there to be extra data in the stream that is an error, because we don't expect there to be any extra data, and that data might be something we're discarding when we shouldn't be.
It's helpful to have functions that do this for us, so that the caller doesn't have to do this themselves.
The _to_end style functions are aligned with an existing pattern in the std::io::Read trait, where functions that end in _to_end read the stream all the way to the end. Although the function names do read a little odd. There might be a better name for this, but I haven't found it.

Rust: Add read xdr to end fns

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Rust: Type Opaque as BytesM and String as StringM
The ultimate goal of this change is to get us to a place where we can improve the rendering of XDR Strings and XDR Opaque types in stringified renderings of XDR values either in Rust Debug form or in JSON.
Rust has a powerful type system, but also some limitations that haven't been worked out yet, and so because we put Strings, Opaques (Bytes), and arrays for types into the same Rust type, VecM, we cannot specialize their rendering. This results in the default rendering being used by whatever rendering system is rendering the type. Most rendering systems in Rust, like the default Debug implementations, and serde_json, all rely on using types to distinguish how the rendering occurs, or they require adding attributes to field attributes …

Rust: Type Opaque as BytesM and String as StringM

---

Makefile
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Use u32::from for converting bools to u32 in Rust generated code.
To maintain the xdrgen generated Rust code as passing clippys checks.

Rust: Fix clippy lint warning introduced in Rust 1.65

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Bundling a few small changes together:
- Add additional functions for reading vectors of xdr that are base64 encoded data. **Why:** So that we can stream decode base64 encoded files without having to convert them to strings first.
- Add a few functions for reading base64 and iter reading to the `Type`. **Why:** So that the type is more in line with other types it wraps in terms of capabilities.
- Removed the enum serde tagging of the `Type` type. **Why:** So that when it serialized to JSON the `Type` part disappears and the inner type is all that is rendered. Most of the time when we are using `Type` the goal is to get at the inner type, the outer type is an implementation detail.
- Add a `Frame<T>` type that can decode framed XDR in a stream. **Why:** For conveniently decoding things …

Rust: Add additional fns and types

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Change JSON format from camelCase to snake_case in the Rust generated output.
Close #145

Rust: Change JSON format from camelCase to snake_case

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Use relative `use` refs in Rust generated code.
To allow the generated code to be used in places where it is not in the root crate module.

Rust: Use relative use refs

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Move variables in write! and panic! macro calls into the format string.
Clippy in Rust 1.66 started requiring variables to be specified in the string rather than as an argument.

Rust: Fix clippy warnings introduced in Rust 1.66

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Instruct clippy to ignore match statements with identical arms in the long type functions.
The arms are identical, and for code gen it is easier of they are duplicates rather than joined.

Rust: Fix clippy warning

---

lib/xdrgen/generators/go.rb
spec/output/generator_spec_go/test.x/MyXDR_generated.go

Closes #154 
Also, for types we can't or don't know how to decode directly,  make sure we always call `Decode()` on a pointer reference
You can see the result of this PR at https://github.com/stellar/go/pull/4818

Golang: add bool support to EncodeTo() and DecodeFrom()

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/Cargo.lock
lib/xdrgen/generators/rust/Cargo.toml
lib/xdrgen/generators/rust/src/lib.rs
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

This is the xdrgen side of changed needed for https://github.com/stellar/rs-soroban-env/issues/861
Generated rs-stellar-xdr: https://github.com/stellar/rs-stellar-xdr/pull/281
The corresponding env PR is https://github.com/stellar/rs-soroban-env/pull/904
- Adds a new trait `DepthLimiter` and implements it on two new structures `DepthLimitedRead` and `DepthLimitedWrite`, which replace the normal `R: Read` and `W: Write` in `[Read,Write]Xdr`. 
- The depth limiter provides a guard that automatically increases and decreases a counter on `enter` and `leave`. Thus limiting the number of recursions on `[read_ write_]xdr` calls. 
- Defines a `pub const DEFAULT_MAX_DEPTH_LIMIT: u32` which is used for scenarios where DepthLimited structure is constructed internally ( `from_xdr(bytes)` and …

Add `DepthLimiter` and adapt to the Read/WriteXDR

---

lib/xdrgen/generators/javascript.rb

Closes #153.
Note: I'm still testing the end-to-end with js-stellar-base.

Escape certain reserved terms when building member functions

---

Gemfile.lock
lib/xdrgen/generators/javascript.rb
lib/xdrgen/version.rb
spec/output/generator_spec_javascript/union.x/MyXDR_generated.js

The JavaScript generator handles unions like this:
```js
// === xdr source ============================================================
//
//   union StoredTransactionSet switch (int v)
//   {
//   case 0:
//   	TransactionSet txSet;
//   case 1:
//   	GeneralizedTransactionSet generalizedTxSet;
//   };
//
// ===========================================================================
xdr.union("StoredTransactionSet", {
switchOn: xdr.int(),
switchName: "v",
switches: [
[0, "txSet"],
[1, "generalizedTxSet"],
],
arms: {
txSet: xdr.lookup("TransactionSet"),
generalizedTxSet: xdr.lookup("GeneralizedTransactionSet"),
},
});
```
which results in uncallable methods (i.e. you can't do `let txset = StoredTransactionSet.0()`). This PR renames switches that are made of only digits to have underscores …

JS: Make numeric union arms callable by adding a `_` prefix

---

Gemfile.lock
lib/xdrgen/generators/javascript.rb
lib/xdrgen/version.rb
spec/output/generator_spec_javascript/union.x/MyXDR_generated.js

This alleged fix is a product of a fundamental misunderstanding of the way that js-xdr works in terms of building the Union structures. In fact, this breaks them. The way that you can initialize numeric unions such as `TransactionMeta`, whose definition is:
```xdr
union TransactionMeta switch (int v)
{
case 0:
OperationMeta operations<>;
case 1:
TransactionMetaV1 v1;
case 2:
TransactionMetaV2 v2;
case 3:
TransactionMetaV3 v3;
};
```
is by passing the enum switch and its value to the constructor, e.g.
```javascript
//   case 0:
//       OperationMeta operations<>;
//   case 1:
//       TransactionMetaV1 v1;
//   case 2:
//       TransactionMetaV2 v2;
//   case 3:
//       TransactionMetaV3 v3;
//   };
```
is by passing the enum switch and its value to the constructor, e.g.
```javascript …
```

Revert "JS: Make numeric union arms callable by adding a `_` prefix"

---

lib/xdrgen/generators/go.rb
spec/output/generator_spec_go/block_comments.x/MyXDR_generated.go
spec/output/generator_spec_go/const.x/MyXDR_generated.go
spec/output/generator_spec_go/enum.x/MyXDR_generated.go
spec/output/generator_spec_go/nesting.x/MyXDR_generated.go
spec/output/generator_spec_go/optional.x/MyXDR_generated.go
spec/output/generator_spec_go/struct.x/MyXDR_generated.go
spec/output/generator_spec_go/test.x/MyXDR_generated.go
spec/output/generator_spec_go/union.x/MyXDR_generated.go

See https://github.com/stellar/go/pull/5057 for an example of the generated output
Depends on https://github.com/stellar/go-xdr/pull/18

golang: Enforce maximum decoding depth

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs

Allocate memory for vararray as needed in Rust generated code.

Allocate memory for vararray as needed in Rust

---

README.md
lib/xdrgen/cli.rb
lib/xdrgen/compilation.rb
lib/xdrgen/generators/base.rb
lib/xdrgen/generators/rust.rb
spec/lib/xdrgen/generator_spec.rb
spec/lib/xdrgen/rust_spec.rb
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Add option for rust generator to allow the generator to be run without generating str conversions for a list of types.
To allow us to run the generator without having it generate str conversions for some types that we are going to provide hand written conversions for.
For #171
For #175
For #176

Add option for rust generator for custom str implementations for types

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Add length limits to the Rust generated code.
Simplified the existing DepthLimitedRead/Write structs, combining them into one, and renaming them to Limited. Added the Limits type that captures the limits and made it a required input to functions that used to collect the depth limit.
To avoid preallocating memory when parsing will ultimately fail because the message being parsed doesn't contain sufficient data for the parse to succeed.
Close #174
Alternative to https://github.com/stellar/xdrgen/pull/178

Rust: Add length limits

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Change Type::from_xdr_base64 fn to accept any type that as-refs to [u8] instead of accepting a String.
There's three reasons.
The first is that by accepting a `String` we're requiring the caller to provide an owned value to the function. The function doesn't need an owned value, so the request for an owned value is unnecessary.
The second is that by accepting a `String` we're requiring that the caller to provide a value that is stored in memory allocated by the global allocator (the heap). Again this is unnecessary.
The third is that the base64 may not be stored in a string, it might have been communicated over a network or some other medium where we've got it in bytes, and converting it to a string before passing it to the decoder is unnecessary work that has fallible cases to handle …

Fix param of Type::from_xdr_base64

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Change StringM Debug, String, and Debug representations to escaped printable-ASCII. But keep ability to convert to/from UTF-8 Strings.
The `Debug`, `Display`, and `FromStr` functions are intended for converting to and from a reliable String representation for the type. Today these do not render reliable String representations because `StringM` can actually contains arbitrary byte sequences that have no representation in ASCII or UTF-8.
These representations are also used in the XDR<>JSON encoding, and so there are values of StringM that are not roundtrip convertible.
It is however reasonable that someone would want to convert to and from a StringM type using Unicode/UTF-8 String values. The TryFrom/TryInto conversions with String have been retained for this, as well as some inherent …

Change StringM Debug, String, and Debug representations to escaped

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Render doc comments on types in the Rust generated code.
The generator generates regular comments that don't show up in the docs on docs.rs.
It should generate doc comments so that the comments display.

Rust: Render doc comments on types

---

lib/xdrgen/generators/java.rb
lib/xdrgen/generators/java/XdrString.erb
spec/output/generator_spec_java/block_comments.x/AccountFlags.java
spec/output/generator_spec_java/block_comments.x/XdrString.java
spec/output/generator_spec_java/const.x/XdrString.java
spec/output/generator_spec_java/enum.x/Color.java
spec/output/generator_spec_java/enum.x/Color2.java
spec/output/generator_spec_java/enum.x/MessageType.java
spec/output/generator_spec_java/enum.x/XdrString.java
spec/output/generator_spec_java/nesting.x/UnionKey.java
spec/output/generator_spec_java/nesting.x/XdrString.java
spec/output/generator_spec_java/optional.x/XdrString.java
spec/output/generator_spec_java/struct.x/XdrString.java
spec/output/generator_spec_java/test.x/Color.java
spec/output/generator_spec_java/test.x/Nester.java
spec/output/generator_spec_java/test.x/XdrString.java
spec/output/generator_spec_java/union.x/UnionKey.java
spec/output/generator_spec_java/union.x/XdrString.java

This PR is very simple, I think it's more appropriate to throw an `IllegalArgumentException` here.

Java: throw a more appropriate exception.

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Add deserialize_json fn to the Type object for deserializing multiple types in json from a stream when the type variant is known at runtime not compile time. Also rename read_json to from_json in a backwards compatible way.
In the CLI we need to be able to decode JSON for arbitrary types at runtime in much the same way we can decode XDR for arbitrary types so the commands have symmetry.
We support decoding XDR to JSON for streams, but not in reverse.
There's a function today `read_json` that can decode a JSON object into an arbitrary Type variant, but because of the interface the function used it only does so for a single JSON object and expects an EOF to occur.
For streams we need to use the more complex serde interface to deserialize multiple objects from the stream.
The read_json fn is …

Rust: Add fn for deserializing multiple types in json from a stream

---

Gemfile.lock
xdrgen.gemspec

See https://stackoverflow.com/questions/79360526/uninitialized-constant-activesupportloggerthreadsafelevellogger-nameerror
Running xdrgen will result in the following error, and this PR will fix the issue.
```
/usr/local/rvm/gems/default/gems/activesupport-6.1.6.1/lib/active_support/logger_thread_safe_level.rb:16:in `<module:LoggerThreadSafeLevel>': uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)
Logger::Severity.constants.each do |severity|
^^^^^^^^^^
from /usr/local/rvm/gems/default/gems/activesupport-6.1.6.1/lib/active_support/logger_thread_safe_level.rb:9:in `<module:ActiveSupport>'
from /usr/local/rvm/gems/default/gems/activesupport-6.1.6.1/lib/active_support/logger_thread_safe_level.rb:8:in `<top (required)>'
from …
```

chore: pin 'concurrent-ruby' to a working version.

---

.github/workflows/ruby.yml
Makefile

Adds a new 'make' job to the GitHub workflow to test the local Makefile.
Pin the make job to ruby 3.3.
Ensures that the Makefile works correctly and generates expected test outputs during continuous integration. I noticed in @overcat's PR below that the tests pass in CI, but the Makefile doesn't locally.
- https://github.com/stellar/xdrgen/pull/206
As @overcat pointed out in that other PR, the Makefile doesn't pin to a version of ruby and xdrgen currently doesn't build with ruby 3.4.

Add Make Job to GitHub Workflow

---

lib/xdrgen/generators/rust/src/types.rs
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Add iter_mut method to VecM struct in the Rust generated code.
Enables direct modification of elements within a VecM without needing to replace the entire collection.
Close #209

Rust: Add iter_mut method to VecM struct

---

lib/xdrgen/generators/rust.rb
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs

Add custom string deserializers for structs to fallback to their structural form.
Improves backward compatibility by allowing deserialization from both string representations and original struct JSON maps. At this point XDR-JSON is in use and while the format can always break between protocol versions, when we make significant widespread changes like changing Int128Parts to be a string, it creates a better experience for folks if previous forms like `{"hi":0,"lo":1}` continue to deserialize.
This is only supported for structs for now, because it's the only type of XDR type that we are currently adding a string form for (https://github.com/stellar/rs-stellar-xdr/pull/441), and structs are also the only form that can be defined generally in a way that is unambiguous between the two. XDR …

Allow custom str deser impl fallback to their structure in JSON

---

lib/xdrgen/generators/rust.rb
lib/xdrgen/generators/rust/src/types.rs
lib/xdrgen/output_file.rb
spec/output/generator_spec_rust/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust/const.x/MyXDR.rs
spec/output/generator_spec_rust/enum.x/MyXDR.rs
spec/output/generator_spec_rust/nesting.x/MyXDR.rs
spec/output/generator_spec_rust/optional.x/MyXDR.rs
spec/output/generator_spec_rust/struct.x/MyXDR.rs
spec/output/generator_spec_rust/test.x/MyXDR.rs
spec/output/generator_spec_rust/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_jsonschema_impls/union.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/block_comments.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/const.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/enum.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/nesting.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/optional.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/struct.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/test.x/MyXDR.rs
spec/output/generator_spec_rust_custom_str_impls/union.x/MyXDR.rs

Add handling for 64-bit integers in XDR structures to ensure they are serialized as strings in JSON. Adds the handling in the cases of struct fields, union (enum) fields, and typedef (unamed struct) fields.
JavaScript has limited precision for integers larger than 53 bits, requiring large integers to be represented as strings to prevent data loss. Today those integers are rendered as numbers which requires that folks use non-native JSON parsers in JavaScript runtimes.
Close #181

Rust: Serialize 64-bit integers as strings in xdr-json

---

lib/xdrgen/compilation.rb
spec/lib/xdrgen/custom_generator_spec.rb

Add support for providing custom generators to the XDR compilation process.
To make it possible to use the xdrgen library to generate xdr with generators not defined in the library. As a first step for moving the generators to their respective repos. Some generators, such as the Rust generator and the JS generator, are tightly coupled with the library they generate code for. Because of that the separation of the generator into the xdrgen repo makes for an awkward development cycle, and since the code generated is not particularly portable, little benefit.
Related:
- https://github.com/stellar/stellar-protocol/discussions/1738
- https://github.com/stellar/rs-stellar-xdr/pull/449
- https://github.com/stellar/xdrgen/pull/221

Add support for custom XDR generators

---

lib/xdrgen/compilation.rb
spec/lib/xdrgen/compilation_spec.rb

Add validation to ensure at least one source file is provided for compilation.
Prevents silent failure when an empty list of source paths is provided.

Error on no .x source paths during compilation
